### ISSUE TITLE
Private registry not taken into account for `helm-job-image`

### ISSUE THREAD

**Issue by abarry-gn** [rancher/prometheus-federator#10]
**Cluster Setup**
- Kubernetes version: 1.20.15
- Rancher version : 2.6.5 
- Type of Cluster: RKE1
- Installation option (Helm Chart / Custom Installation):
   - If Helm Chart, did you supply any non-default values? If so, what values did you supply:
   I have system-default-registry set on my Rancher so all my images should be deployed from this registry. 

**Describe the bug**
When I deploy prometheus-federator with default values, then when I add a new project monitor, the job that deploys the monitoring component is not using my private registry. It is using the default image value "rancher/klipper-helm:v0.7.0-build20220315". 

I find out that the issue is because of an extra space before the line [here](https://github.com/rancher/prometheus-federator/blob/0798a8f46069afff05ded6ebd4cd6564c5989634/charts/prometheus-federator/0.1.0/charts/helmProjectOperator/templates/deployment.yaml#L79). 

**To Reproduce**
- Enable Cluster monitoring V2
- Go to Apps and deplo prometheus-federator
- Go Monitoring > Project Monitors, then Create a new project monitor and select the project where to deploy the monitoring
- Go to Jobs and check its image

**Result**
Job is using the default image without private registry and job's pod get stuck in pulling the image since there is no internet connection. 

**Expected Result**
Prometheus, Grafana and Alertmanager deployed in the selected project

**Additional information**
When I manually edit the deployment of prometheus-federator and remove the extra space before `- --helm-job-image....` everything works fine as expected. 

The prometheus-federator deployment.yml file should be: 

```
76 {{- if not .Values.helmController.enabled }}
77           - --disable-embedded-helm-controller
78 {{- else }}
79           - --helm-job-image={{ template "system_default_registry" . }}{{ .Values.helmController.job.image.repository }}:{{ .Values.helmController.job.image.tag }}
80 {{- end }}
```

Instead of 
```
76 {{- if not .Values.helmController.enabled }}
77           - --disable-embedded-helm-controller
78 {{- else }}
79            - --helm-job-image={{ template "system_default_registry" . }}{{ .Values.helmController.job.image.repository }}:{{ .Values.helmController.job.image.tag }}
80 {{- end }}
```

**Comment by PlayMTL** [comment]
I have the same issue. Deployment of Project Monitoring v2 in my airgaped environment currently not possible.
Is there a workaround available?

**Comment by barryboubakar** [comment]
> I have the same issue. Deployment of Project Monitoring v2 in my airgaped environment currently not possible. Is there a workaround available?
My current workaround is to go to `Workload` > `Deployments` and edit the `prometheus-federator` deployment. Remove the space before `- --helm-job-image`  (Line 215) so that it could be aligned with other parameters. 

Another workaround could be cloning the helm chart repo, fixing the typo and pushing it to a local helm chart repository... this is not usable for me, I prefer waiting the fix ;)

**Comment by aiyengar2** [comment]
Fixed in https://github.com/rancher/prometheus-federator/pull/15!

**Comment by aiyengar2** [comment]
Fix ported to rancher/charts: https://github.com/rancher/charts/pull/1997

**Comment by MKlimuszka** [comment]
This is already released, but QA still needs to validate it

**Comment by aiyengar2** [comment]
Closing out this issue in favor of the rancher/rancher issue where QA validation can be performed.
