### ISSUE TITLE
[Tech Debt] Follow up on repo reorg

### ISSUE THREAD

**Issue by mallardduck** [rancher/prometheus-federator#109]
This Issue is to track follow-up tasks after this was merged: https://github.com/rancher/prometheus-federator/pull/97

- [x] Migrate issues from HPO repo to this one and properly label,
- [x] Create/Get reviewed/merge PR to clean up CI and ensure all proper release artifacts,
- [x] Tag a new release `v0.4.3-rc.2` (note this is still a "universal" rancher tagged release; could be for 2.8+),
- [x] subsequently ensure necessary charts are updated and in `rancher/charts`

**Comment by mallardduck** [comment]
Follow up PR created, waiting for review to merge: https://github.com/rancher/prometheus-federator/pull/110

**Comment by mallardduck** [comment]
Created Charts PR: https://github.com/rancher/charts/pull/4588

**Comment by mallardduck** [comment]
For QA, this is testable as version [`105.0.0-rc.1+up0.4.3-rc.1`](https://github.com/rancher/charts/tree/dev-v2.10/charts/prometheus-federator/105.0.0-rc.1%2Bup0.4.3-rc.1)

**Comment by pankajsqe** [comment]
Prometheus Federator : 105.0.0-rc.1+up0.4.3-rc.1 has been validated on 2.10.0-alpha7


![Image](https://github.com/user-attachments/assets/0d4aa923-15e3-4524-b8bf-d483667377fc)
![Image](https://github.com/user-attachments/assets/eb7e0598-a9ba-451e-ba18-6b17aa9871d0)
