### ISSUE TITLE
typo in label?

### ISSUE THREAD

**Issue by rgcosma** [rancher/prometheus-federator#123]
https://github.com/search?q=repo%3Arancher%2Fprometheus-federator%20prometheus1&type=code looks like a typo thatțs been in there since 0.4.0

**Comment by mallardduck** [comment]
The Charts side (that ships the fix): https://github.com/rancher/charts/pull/4872
Chart RC to test: PromFed 105.1.0-rc.1+up0.4.5-rc.1

**Comment by pankajsqe** [comment]
typo error has been fixed and verified on [PR](https://github.com/rancher/prometheus-federator/pull/132) with below config.

Details
Rancher : V2.11-head
PromFed : 105.1.0-rc.1+up0.4.5-rc.1
Cluster : v1.31.1+rke2r1
