### ISSUE TITLE
Broken links in gettingstarted.md prometheus-federator docs.

### ISSUE THREAD

**Issue by stalin4suse** [rancher/prometheus-federator#19]
The link in the following sentence is broken `see the (see the README.md on the Helm Char) for more information on how to optimally configure rancher-monitoring to work with Prometheus Federator).`

The link embedded is https://github.com/rancher/prometheus-federator/blob/main/docs/packages/prometheus-federator/charts/README.md which takes to a 404 page.

**Comment by aiyengar2** [comment]
Fixed and merged, thanks @stalin4suse
