### ISSUE TITLE
Templating Grafana Credentials in rancher-project-monitoring

### ISSUE THREAD

**Issue by hazem-bouaziz** [rancher/prometheus-federator#33]
Hello All!, 

I tried deploying a ProjectHelmChart CR and customize my configs for Grafana's Credentials;

**TO-DO:** 
I was based on the `question.yaml` file on rancher-project-monitoring repository 
The actual value referred there are [`grafana.admin.adminUser`](https://github.com/rancher/prometheus-federator/blob/8a8511b12be8fa6afec6574c5de0254915b2c309/charts/rancher-project-monitoring/0.2.0-rc1/questions.yaml#L14) & [`grafana.admin.adminPassword`](https://github.com/rancher/prometheus-federator/blob/8a8511b12be8fa6afec6574c5de0254915b2c309/charts/rancher-project-monitoring/0.2.0-rc1/questions.yaml#L19)

**EXPECTED:**
While it needs to be set to: 

- [`grafana.adminUser`](https://github.com/rancher/prometheus-federator/blob/0798a8f46069afff05ded6ebd4cd6564c5989634/charts/rancher-project-monitoring/0.1.0/charts/grafana/templates/secret.yaml#L16)
- [`grafana.adminPassword`](https://github.com/rancher/prometheus-federator/blob/0798a8f46069afff05ded6ebd4cd6564c5989634/charts/rancher-project-monitoring/0.1.0/charts/grafana/templates/secret.yaml#L18)

**Comment by aiyengar2** [comment]
Good catch! It does seem like the `questions.yaml` has the wrong field here as those two fields are top-level fields in the Grafana subchart, as you mentioned:

https://github.com/rancher/prometheus-federator/blob/8a8511b12be8fa6afec6574c5de0254915b2c309/charts/rancher-project-monitoring/0.2.0-rc1/charts/grafana/values.yaml#L367-L368

cc: @ronhorton

**Comment by aiyengar2** [comment]
Fixed in `0.2.0-rc2`

**Comment by hazem-bouaziz** [comment]
Hi @aiyengar2 
is there some release note for the charts of prometheus-federator & rancher-project-monitoring 
and the compatibility with rancher version ?
