### ISSUE TITLE
Accessing Services with Rancher-UI  

### ISSUE THREAD

**Issue by hazem-bouaziz** [rancher/prometheus-federator#34]
**Cluster Setup**
- Kubernetes version: v1.21
- Type of Cluster: EKS
- Installation option: Custom Installation
   - installation via manifests
   
**Describe the bug**
I've tried to install a `ProjectHelmChart` Kind using manifests, enabling the Grafana, Prometheus & Federations components and Disabling the AlertManager Instance (For Some [issue](https://github.com/rancher/prometheus-federator/commit/65032b2a9d3d71d2d3436ceee4f635d654bf0471) related to `ExternalUrl` attribute) .
The problem I got that Rancher-UI is blocking the Access to my services (of Grafana & Prometheus) via the UI even tho the access to service manually works super well

![image](https://user-images.githubusercontent.com/115023126/205705475-a459a39c-b370-477d-ba1e-aefecf69bdaa.png)

**To Reproduce**
Fixing the Access to Services with UI

**Comment by aiyengar2** [comment]
@hazem-bouaziz have you filled in the `global.cattle.*` fields shown here?

https://github.com/rancher/prometheus-federator/blob/8a8511b12be8fa6afec6574c5de0254915b2c309/charts/prometheus-federator/0.2.0-rc1/values.yaml#L11-L13

In a Rancher installation, these fields are necessary in order for the services to be properly configured. These are usually set by the Apps & Marketplace UI on a Helm install but would not be automatically supplied in a custom installation.

Specifically, the clusterId and url are necessary to construct the dashboard-values ConfigMap shown here:

https://github.com/rancher/prometheus-federator/blob/8a8511b12be8fa6afec6574c5de0254915b2c309/charts/rancher-project-monitoring/0.2.0-rc1/templates/dashboard-values-configmap.yaml#L18-L56

This is then expected to be on the ProjectHelmChart's `.status.dashboardValues`, which is where the Rancher UI picks up the URL values to be linked to here.

Start by checking `.status.dashboardValues` on the ProjectHelmChart to see if it's missing though!

**Comment by hazem-bouaziz** [comment]
Thanks @aiyengar2 
Yes, It works fine for me ! 
I was just facing some trouble with fleet to inject the correct values for the field `global.cattle.*` 
I will close this issue
