### ISSUE TITLE
Wrong URL for metrics in local cluster

### ISSUE THREAD

**Issue by eumel8** [rancher/prometheus-federator#44]
**Cluster Setup**
- Kubernetes version: v1.24.8+k3s1
- Type of Cluster (RKE1, RKE2, k3s, EKS, GKE, AKS, OKE, etc): k3s
- Installation option (Helm Chart / Custom Installation):
   - If Helm Chart, did you supply any non-default values? If so, what values did you supply:

```
$ helm -n cattle-system get values rancher
USER-SUPPLIED VALUES:
auditLog:
  level: 2
bootstrapPassword: xxxxxx
certmanager:
  version: 1.8.1
hostname: xxxxxxx
ingress:
  enabled: true
  tls:
    source: letsEncrypt
letsEncrypt:
  email: xxxxxxxxxxx
  ingress:
    class: traefik
rancherImage: mtr.devops.telekom.de/rancher/rancher
rancherImageTag: v2.7.0
replicas: 2
systemDefaultRegistry: mtr.devops.telekom.de
```
   
**Describe the bug**
rancher-monitoring-101.0.0+up19.0.3
prometheus-federator-1.0.0+up0.1.1

When I install Project Monitoring on the local Cluster in Rancher, the metric charts on the front dashboard and in Grafana are empty.
It seems the called URL is wrong:

<rancher-server>/api/v1/namespaces/cattle-project-p-6wlzz-monitoring

instead

<rancher-server>/k8s/clusters/local/api/v1/namespaces/cattle-project-p-6wlzz-monitoring

Rancher is installed in multi-cluster mode. On the downstream cluster it'ts working.

**To Reproduce**
Install Prometheus Federator and Project Monitoring with default settings via Rancher UI

**Result**

Metrics empty

**Expected Result**

Metrics visible

**Comment by bashofmann** [comment]
This issue is not related to the prometheus-federator itself, but to how it's used in rancher/dashboard. I created https://github.com/rancher/dashboard/issues/8346 to track this there. PR to fix the URL: https://github.com/rancher/dashboard/pull/8347.

**Comment by eumel8** [comment]
thx @bashofmann 
will close this issue here
