### ISSUE TITLE
[project-monitoring] Summary dashboard has no metrics for Disk I/O

### ISSUE THREAD

**Issue by eumel8** [rancher/prometheus-federator#59]
**Describe the bug**
On all Project Monitoring installations the graph for Disk I/O are empty. The underlying dashboard Rancher/Pod has also no metrics. Prometheus has some metrics for container_fs_writes_bytes_total and container_fs_read_bytes_totak, but it seems there are [some changes ](https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/737), linked with [this pr](https://github.com/openshift/cluster-monitoring-operator/pull/1554), also mentioned in this [OpenShift Issue](https://bugzilla.redhat.com/show_bug.cgi?id=2037513)

**To Reproduce**
I couldn't full reproduce the issue and what caused the empty metrics exactly. Maybe it needs a device-selector, optional a newer version from upstream (prometheus-federator 0.2.1)

**Result**
empty metrics

**Expected Result**
metrics for disc io on all Kubernetes and Rancher dashboard

SURE-6055

**Comment by MKlimuszka** [comment]
We can check to see if there is an upstream issue and link it, but beyond that it is out of our control.

**Comment by bashofmann** [comment]
I think this may be fixed with rancher-monitoring 102.0.0+up40.1.2. I tested it with RKE1 v1.24.10.

@eumel8 Can you check if this is fixed with new monitoring/prometheus-federator version for you as well?

**Comment by aiyengar2** [comment]
Probably a dup of https://github.com/rancher/rancher/issues/38934, which was ported into the latest rancher-monitorng chart (which was brought into prometheus-federator as well). 

@eumel8 feel free to open up a new issue if you are still seeing this, closing this out since it is probably fixed

**Comment by eumel8** [comment]
seems fixed on the updated 102.0.0+up40.1.2 as of today on our clusters. thx, @aiyengar2
