### ISSUE TITLE
Reorg the `helm-locker` repo to merge into `helm-project-operator` repo

### ISSUE THREAD

**Issue by mallardduck** [rancher/prometheus-federator#94]
Per title, this issue is to track phase 1 of our project monitoring re-org project.

Essentially in this step we are re-homing the `helm-locker` code into the `helm-project-operator` repo. And the goal is to do so without changing much else that could cause breaking changes at all. So testing/QAing this before we merge is a crucial step to ensure we're not overlooking something.

To test, setup Rancher (ideally 2.10/head) and create a repo:
```
type: git
url: https://github.com/mallardduck/rancher-charts
branch: prom-reorg-test
```

Then you will have access to Prometheus Federator `105.0.0-rc.1+up0.4.2` which has these changes incorporated into the image it uses. This can be used to run the QA tests for prom-federator and rancher-project-monitoring. And once validated we should be more confident when merging these reorganization PRs.

---

The primary PR this is testing is: https://github.com/rancher/helm-project-operator/pull/74
However this waterfalls into: https://github.com/rancher/prometheus-federator/pull/93
And subsequently the `rancher/charts` branch mentioned above; however this PR is meant for demo only and will be recreated at merge time. Ideally, these changes will rolling out along side with the 2.10 monitoring rebase.

**Comment by pankajsqe** [comment]
Passed : Blocker issue `#47155 `was resolved and retested. regression test on project-monitoring from prometheus-federator was completed.!

rancher v2.10-head
cluster k3s
prom-fed 105.0.0-rc.1+up0.4.2
charts repo :

[Image](https://github.com/user-attachments/assets/5de1c060-d072-4a48-9bb4-ad7a7fb6d858)
![Image](https://github.com/user-attachments/assets/7b9ff08f-aacc-4deb-ab35-ac7858f4ef26)
![Image](https://github.com/user-attachments/assets/14823253-fe2f-4bec-854f-3af293214828)
